### Column width
setColWidths(wb, i, cols = "A", widths = 2.33)
setColWidths(wb, i, cols = "B", widths = 1.67)
setColWidths(wb, i, cols = "C", widths = 10)
setColWidths(wb, i, cols = "D", widths = 10)
setColWidths(wb, i, cols = "E", widths = 10)
setColWidths(wb, i, cols = "F", widths = 10)
setColWidths(wb, i, cols = "G", widths = 14.33)
setColWidths(wb, i, cols = "H", widths = 1)
setColWidths(wb, i, cols = "I", widths = 1)
setColWidths(wb, i, cols = "J", widths = 3.33)
setColWidths(wb, i, cols = "K", widths = 17)
setColWidths(wb, i, cols = "L", widths = 9.67)
setColWidths(wb, i, cols = "M", widths = 9.67)
setColWidths(wb, i, cols = "N", widths = 8.33)
setColWidths(wb, i, cols = "O", widths = 8.67)
setColWidths(wb, i, cols = "P", widths = 2.33)
setColWidths(wb, i, cols = "Q", widths = )

### Row width
setRowHeights(wb, i, rows = 1, heights = 0) 
setRowHeights(wb, i, rows = 2, heights = 12)
setRowHeights(wb, i, rows = 3, heights = 27.75)
setRowHeights(wb, i, rows = 4, heights = 11.25)
setRowHeights(wb, i, rows = 5, heights = 25.5)
setRowHeights(wb, i, rows = 6, heights = 14.25)
setRowHeights(wb, i, rows = 7, heights = 27.75)
setRowHeights(wb, i, rows = 8, heights = 12)
setRowHeights(wb, i, rows = 9, heights = 19.5)
setRowHeights(wb, i, rows = 10:16, heights = 34.5)
setRowHeights(wb, i, rows = 15, heights = 18.75)
setRowHeights(wb, i, rows = 16, heights = 27.75)
setRowHeights(wb, i, rows = 17, heights = 17.25)
setRowHeights(wb, i, rows = 18, heights = 72)
setRowHeights(wb, i, rows = 20, heights = 30)
setRowHeights(wb, i, rows = 21, heights = 12)
setRowHeights(wb, i, rows = 22, heights = 16)
setRowHeights(wb, i, rows = 23, heights = 16.5)
setRowHeights(wb, i, rows = 24, heights = 21)
### table rows
setRowHeights(wb, i, rows = 37, heights = 39.75)
setRowHeights(wb, i, rows = 38, heights = 24.75)
setRowHeights(wb, i, rows = 39, heights = 72.75)
setRowHeights(wb, i, rows = 40, heights = 19.5)
setRowHeights(wb, i, rows = 41, heights = 39.75)
setRowHeights(wb, i, rows = 42, heights = 13.5)
setRowHeights(wb, i, rows = 43, heights = 27.75)
### Table rows
setRowHeights(wb, i, rows = c(79, 80), heights = 15.75)